title: KOROKKE BLOG
email: realkorokke@outlook.com
description: |
  고로케의 블로그입니다
baseurl: ''
#url: 'https://korokke.github.io'
timezone: Asia/Seoul

repository: korokke/korokke.github.io

#permalink: /:year/:month/:day/:title/
permalink: /:year-:month-:day-:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]

asset_url: /assets
facebook:
  app_id: '1204347326263800'
  username: realkorokke
twitter:
  username: real_korokke
github_url:
  username: korokke
